# https://github.com/sttz/install-unity/blob/next/sttz.InstallUnity/Installer/Scraper.cs
# https://public-cdn.cloud.unity3d.com/hub/prod/releases-linux.json

language: minimal
env:
  global: 
    - UNITY_VERSION="2019.1.0b8"
    - UNITY_DOWNLOAD_URL="https://beta.unity3d.com/download/0862b00eb5a3/LinuxEditorInstaller/Unity.tar.xz"
    - UNITY_EDITOR_INSTALL_FOLDER="$HOME/Unity/Hub/Editor/$UNITY_VERSION"
    - UNITY_ACTIVATION_FILE="$HOME/unity-license.alf"
    - UNITY_EDITOR_BINARY="$UNITY_EDITOR_INSTALL_FOLDER/Editor/Unity"
    - UNITY_EDITOR="$UNITY_EDITOR_BINARY -quit -batchmode -logfile -nographics"
cache:
  directories:
    - "$UNITY_EDITOR_INSTALL_FOLDER"
install:
  - ls $UNITY_EDITOR_INSTALL_FOLDER
  - sudo apt-get update
  - sudo apt-get install libnss3 libgtk2.0-0 libsoup2.4-1 libarchive13 libgconf-2-4 lib32stdc++6 libcanberra-gtk-module p7zip-full desktop-file-utils xdg-utils libfontconfig1 libfreetype6 zenity
  - |
    if [ ! -f "$UNITY_EDITOR_BINARY" ]; then
      mkdir -p ~/unity-download-tmp
      cd ~/unity-download-tmp
      wget "$UNITY_DOWNLOAD_URL"
      tar xf Unity.tar.xz -C "$UNITY_EDITOR_INSTALL_FOLDER"
    fi
  - $UNITY_EDITOR -createManualActivationFile -username $UNITY_USERNAME -password $UNITY_PASSWORD || true
  - find -name "Unity*" -exec mv {} $UNITY_ACTIVATION_FILE \;
  - $UNITY_EDITOR -manualLicenseFile $UNITY_ACTIVATION_FILE || true
script:
  - cd $TRAVIS_BUILD_DIR
  - $UNITY_EDITOR -executeMethod MyEditorBuild.PerformBuild || true