language: minimal
install:
- sudo apt-get update
- sudo apt-get install libnss3
- wget https://public-cdn.cloud.unity3d.com/hub/prod/UnityHubSetup.AppImage
- chmod +x UnityHubSetup.AppImage
- ./UnityHubSetup.AppImage
script:
- echo "foo"