# https://github.com/sttz/install-unity/blob/next/sttz.InstallUnity/Installer/Scraper.cs
# https://public-cdn.cloud.unity3d.com/hub/prod/releases-linux.json

language: minimal
env:
  UNITY_VERSION="2019.1.0b8"
  UNITY_DOWNLOAD_URL="https://beta.unity3d.com/download/0862b00eb5a3/LinuxEditorInstaller/Unity.tar.xz"
  UNITY_EDITOR_INSTALL_FOLDER="$HOME/Unity/Hub/Editor/$UNITY_VERSION"
  UNITY_EDITOR_BINARY="$UNITY_EDITOR_INSTALL_FOLDER/Editor/Unity"
cache:
  directories:
    - $UNITY_EDITOR_INSTALL_FOLDER
install:
  - sudo apt-get update
  - sudo apt-get install libnss3 libgtk2.0-0 libsoup2.4-1 libarchive13 libgconf-2-4 lib32stdc++6 libcanberra-gtk-module p7zip-full desktop-file-utils xdg-utils libfontconfig1 libfreetype6 zenity
  - |
    if [ ! -f "$UNITY_EDITOR_BINARY" ]; then
      mkdir -p ~/unity-download-tmp
      cd ~/unity-download-tmp
      wget "$UNITY_DOWNLOAD_URL"
      tar xf Unity.tar.xz -C "$UNITY_EDITOR_INSTALL_FOLDER"
    fi
script:
  - cd $TRAVIS_BUILD_DIR
  - |
    $UNITY_EDITOR_BINARY \
      -quit \
      -batchmode \
      -logfile \
      -nographics \
      -executeMethod  MyEditorBuild.PerformBuild