language: minimal
install:
  - sudo apt-get update
  - sudo apt-get install libnss3 libgtk2.0-0 libsoup2.4-1 libarchive13 libgconf-2-4 lib32stdc++6 libcanberra-gtk-module p7zip-full desktop-file-utils xdg-utils libfontconfig1 libfreetype6 zenity
  - wget https://public-cdn.cloud.unity3d.com/hub/prod/UnityHubSetup.AppImage
  - chmod +x UnityHubSetup.AppImage
  - ./UnityHubSetup.AppImage
script:
  - echo "foo"