# https://github.com/sttz/install-unity/blob/next/sttz.InstallUnity/Installer/Scraper.cs
# https://public-cdn.cloud.unity3d.com/hub/prod/releases-linux.json

language: minimal
cache:
  directories:
    - $HOME/Unity-installer-2019.1.0b8
install:
  - sudo apt-get update
  - sudo apt-get install libnss3 libgtk2.0-0 libsoup2.4-1 libarchive13 libgconf-2-4 lib32stdc++6 libcanberra-gtk-module p7zip-full desktop-file-utils xdg-utils libfontconfig1 libfreetype6 zenity
  - |
    UNITY_EDITOR_INSTALL_FOLDER = "$HOME/Unity-installer-2019.1.0b8"
    UNITY_EDITOR_TAR = "$UNITY_EDITOR_INSTALL_FOLDER/Unity.tar.xz"
    if [ ! -f "$UNITY_EDITOR_TAR" ]; then
      mkdir -p $UNITY_EDITOR_INSTALL_FOLDER
      cd $UNITY_EDITOR_INSTALL_FOLDER
      wget https://beta.unity3d.com/download/0862b00eb5a3/LinuxEditorInstaller/Unity.tar.xz
    fi
  - mkdir -p ~/Unity/Hub/Editor/2019.1.0b8/Editor
  - tar xf Unity.tar.xz -C ~/Unity/Hub/Editor/2019.1.0b8/Editor
script:
  - cd $TRAVIS_BUILD_DIR
  - |
    ~/Unity/Hub/Editor/2019.1.0b8/Editor/Unity \
      -quit \
      -batchmode \
      -logfile \
      -nographics \
      "$@" \
      -executeMethod  MyEditorBuild.PerformBuild