# https://github.com/sttz/install-unity/blob/next/sttz.InstallUnity/Installer/Scraper.cs
# https://public-cdn.cloud.unity3d.com/hub/prod/releases-linux.json

language: minimal
env:
  global: 
    - UNITY_VERSION="2019.1.0b8"
    - UNITY_DOWNLOAD_URL="https://beta.unity3d.com/download/0862b00eb5a3/LinuxEditorInstaller/Unity.tar.xz"
    - UNITY_EDITOR_INSTALL_FOLDER="$HOME/Unity/Hub/Editor/$UNITY_VERSION"
    - UNITY_ACTIVATION_FILE="$HOME/unity-license.alf"
    - UNITY_EDITOR_BINARY="$UNITY_EDITOR_INSTALL_FOLDER/Editor/Unity"
    - UNITY_EDITOR="$UNITY_EDITOR_BINARY -quit -batchmode -logfile -nographics"
    - UNITY_LICENSE_FOLDER="$HOME/.local/share/unity3d/Unity"
cache:
  timeout: 1000
  directories:
    - "$UNITY_EDITOR_INSTALL_FOLDER"
install:
  - mkdir -p $UNITY_LICENSE_FOLDER
  - openssl aes-256-cbc -K $encrypted_3c1098c58b6f_key -iv $encrypted_3c1098c58b6f_iv -in Unity_v2019.x.ulf.enc -out Unity_v2019.x.ulf -d
  - ls $UNITY_EDITOR_INSTALL_FOLDER
  - |
    if [ ! -f "$UNITY_EDITOR_BINARY" ]; then
      mkdir -p ~/unity-download-tmp
      cd ~/unity-download-tmp
      wget -nv "$UNITY_DOWNLOAD_URL"
      tar xf Unity.tar.xz -C "$UNITY_EDITOR_INSTALL_FOLDER"
    fi
  - $UNITY_EDITOR -createManualActivationFile || true
  - cat "Unity_v$UNITY_VERSION.alf"
  - $UNITY_EDITOR -manualLicenseFile $TRAVIS_BUILD_DIR/Unity_v2019.x.ulf || true
  - sudo apt-get update
  - sudo apt-get install libnss3 libgtk2.0-0 libsoup2.4-1 libarchive13 libgconf-2-4 lib32stdc++6 libcanberra-gtk-module p7zip-full desktop-file-utils xdg-utils libfontconfig1 libfreetype6 zenity
script:
  - cd $TRAVIS_BUILD_DIR
  - $UNITY_EDITOR -executeMethod MyEditorBuild.PerformBuild || true